version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - PORT=6000
    restart: unless-stopped